version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - run:
          name: Clone repo and build dependencies
          command: |
            git clone --recursive https://github.com/k2snowman69/threadily-sample
      - run:
          name: Checkout branch
          command: |
            git fetch --all
            git checkout ${CIRCLE_BRANCH}
            git submodule update --init --recursive
      - run:
          name: Build threadily-sample
          command: |
            cd ./threadily-sample
            make -j2
      - run:
          name: Test threadily-sample
          command: |
            cd ./threadily-sample
            make test
